### ISSUE TITLE
Target: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by erherhh4herh** [ioncodes/dnpatch#7] opened 2017-02-24 03:43 UTC
This is the code snippet. (Yes, I have already confirmed that the "dllpath" is correct)
*START CODE*
patcher = new Patcher(dllPath);
Target target = new Target()
{
Namespace = "-",
Class = "UserData",
Method = "IsPremium",
Indices = new[] { 0, 1, 2, 3, 4, 5, 6, 7 }
};
patcher.RemoveInstruction(target);
patcher.Save(dllPath);
*END CODE*

"patcher.RemoveInstruction(target);" gives "Object reference not set to an instance of an object." error even though I have created an instance of it.

Any help is greatly appreciated!

**Comment by ioncodes** [comment] 2017-02-24 05:58
Hey! Thanks for using my library! I will check your code now and let you know!

**Comment by ioncodes** [comment] 2017-02-24 06:36
Can you join the Gitter chat and send me over the file?

**Comment by ioncodes** [comment] 2017-02-24 08:03
I think I found the bug, look at your code. You set Namespace to "-", by that I think you want to get a Namespace which doesn't have a Name. There are often these, for example here: http://i.imgur.com/w2EA0nP.png
If you mean this, the "-" is just a dummy in decompilers, just replace it with "" (empty string).

Also, just as a tip, I recommend calculating the indices by using the search methods provided, this will guarantee that it will patch it even if it get's updated.

**Comment by ioncodes** [comment] 2017-02-25 10:46
Has the problem been solved?

**Comment by eregri543jkg** [comment] 2017-02-25 20:38
Sorry for the late reply! I went on a trip and haven't had time to be on the computer. (FYI, I made a new account as I have forgotten my login credentials...)

Thank you for your help! I am wanting to access the empty namespace, as Unity-compiled binaries usually contain the meat and potatoes in the default namespace unity assigns (which appears to be the empty one.) Example given here: http://i.imgur.com/7u5yhny.png

It would seem that making the namespace within the target an empty string (or even string.empty, or even null for that matter) doesn't function. Removing the namespace entry from the target doesn't work either.

As for debugging this for yourself, all unity games are compiled in the same way (majority of game code stored in "Assembly-CSharp.dll" in the data>managed folder) The game I am testing this on is a f2p game called "Galactic Junk League" on steam. 

Exception that is thrown on button press:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at dnpatch.PatchHelper.RemoveInstruction(Target target)
   at dnpatch.Patcher.RemoveInstruction(Target target)
   at netPatcherSimple.patch.DoShit() in C:\Users\bungos\Desktop\netPatcherSimple\netPatcherSimple\patch.cs:line 54
   at netPatcherSimple.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\bungos\Desktop\netPatcherSimple\netPatcherSimple\Form1.cs:line 35
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```
(Yes, I have poor code organization/naming methods...)
I am beginning to think that there is something wrong in my code elsewhere, perhaps the way I am getting the dll's location and such. I will continue to experiment with different methods to rule out possible unrelated issues.

Again, thank you so much for your assistance!

**Comment by ioncodes** [comment] 2017-02-25 22:33
No problems! I will try it out now, and tell you in a couple of hours!

**Comment by ioncodes** [comment] 2017-02-26 00:06
Can you tell me the whole classpath of the method IsPremium and it's IL Body?

**Comment by eregri543jkg** [comment] 2017-02-26 02:24
It's in Assembly-CSharp.dll>*empty namespace*>UserData>IsPremium
Screenshot: http://i.imgur.com/c8tbrlE.png
I'm simply returning this value to true. Also, after extensive testing, I have determined that my issue is not related to the way I am finding the file path to "Assembly-CSharp.dll".

EDIT:
I have already tested that returning that bool to true gives you premium in-game (it expires in -75 days XD)
Also, I noticed "WriteReturnBody" is a thing and switched over to it... (very handy, that!)
Still getting an error, though:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at dnpatch.PatchHelper.PatchAndClear(Target target)
at dnpatch.Patcher.WriteReturnBody(Target target, Boolean trueOrFalse)
```
New code snippet: http://i.imgur.com/vOoVeX8.png

**Comment by ioncodes** [comment] 2017-02-26 12:03
Ok, now it's clear what the problem is. IsPremium is not a Method it's a property and the current version of dnpatch does not have the functionality to patch properties and fields. There are 2 ways to do it: Either you patch the methods which call this property or you wait until I upload an update which is able to patch properties.

**Comment by ioncodes** [comment] 2017-02-26 12:54
Refer to this part of the README: https://github.com/ioncodes/dnpatch#patch-properties
This will allow you to rewrite your getter. In the Example project you will find a similar patch which does also target a property called IsPremium and sets it's getter to true: https://github.com/ioncodes/dnpatch/blob/master/Example/Program.cs#L225

I will close this issue, because it works for me. If you have questions feel free to ask me via Gitter or reopen the Issue.

**Closed as completed by ioncodes** 2017-02-26 12:54 UTC
